package com.mcqueen.mcqueen.mapper;

import com.mcqueen.mcqueen.model.RoleAuth;
import com.mcqueen.mcqueen.model.RoleAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    long countByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    int deleteByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    int insert(RoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    int insertSelective(RoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    List<RoleAuth> selectByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    RoleAuth selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RoleAuth record, @Param("example") RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RoleAuth record, @Param("example") RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleAuth record);
}