package com.mcqueen.mcqueen.mapper;

import com.mcqueen.mcqueen.model.RoleInfo;
import com.mcqueen.mcqueen.model.RoleInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Info
     *
     * @mbg.generated
     */
    long countByExample(RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Info
     *
     * @mbg.generated
     */
    int deleteByExample(RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Info
     *
     * @mbg.generated
     */
    int insert(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Info
     *
     * @mbg.generated
     */
    int insertSelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Info
     *
     * @mbg.generated
     */
    List<RoleInfo> selectByExample(RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Info
     *
     * @mbg.generated
     */
    RoleInfo selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RoleInfo record, @Param("example") RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RoleInfo record, @Param("example") RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleInfo record);
}