package com.mcqueen.mcqueen.model;

import java.io.Serializable;
import java.util.Date;

public class RoleAuth implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_Role_Auth.ID
     *
     * @mbg.generated
     */
    private Integer ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_Role_Auth.RoleID
     *
     * @mbg.generated
     */
    private Integer roleID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_Role_Auth.AuthID
     *
     * @mbg.generated
     */
    private Integer authID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_Role_Auth.CreateTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_Role_Auth.LastModifyTime
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_Role_Auth.IsDelete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_Role_Auth.ID
     *
     * @return the value of M_Role_Auth.ID
     *
     * @mbg.generated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_Role_Auth.ID
     *
     * @param ID the value for M_Role_Auth.ID
     *
     * @mbg.generated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_Role_Auth.RoleID
     *
     * @return the value of M_Role_Auth.RoleID
     *
     * @mbg.generated
     */
    public Integer getRoleID() {
        return roleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_Role_Auth.RoleID
     *
     * @param roleID the value for M_Role_Auth.RoleID
     *
     * @mbg.generated
     */
    public void setRoleID(Integer roleID) {
        this.roleID = roleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_Role_Auth.AuthID
     *
     * @return the value of M_Role_Auth.AuthID
     *
     * @mbg.generated
     */
    public Integer getAuthID() {
        return authID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_Role_Auth.AuthID
     *
     * @param authID the value for M_Role_Auth.AuthID
     *
     * @mbg.generated
     */
    public void setAuthID(Integer authID) {
        this.authID = authID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_Role_Auth.CreateTime
     *
     * @return the value of M_Role_Auth.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_Role_Auth.CreateTime
     *
     * @param createTime the value for M_Role_Auth.CreateTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_Role_Auth.LastModifyTime
     *
     * @return the value of M_Role_Auth.LastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_Role_Auth.LastModifyTime
     *
     * @param lastModifyTime the value for M_Role_Auth.LastModifyTime
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_Role_Auth.IsDelete
     *
     * @return the value of M_Role_Auth.IsDelete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_Role_Auth.IsDelete
     *
     * @param isDelete the value for M_Role_Auth.IsDelete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoleAuth other = (RoleAuth) that;
        return (this.getID() == null ? other.getID() == null : this.getID().equals(other.getID()))
            && (this.getRoleID() == null ? other.getRoleID() == null : this.getRoleID().equals(other.getRoleID()))
            && (this.getAuthID() == null ? other.getAuthID() == null : this.getAuthID().equals(other.getAuthID()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastModifyTime() == null ? other.getLastModifyTime() == null : this.getLastModifyTime().equals(other.getLastModifyTime()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_Role_Auth
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getID() == null) ? 0 : getID().hashCode());
        result = prime * result + ((getRoleID() == null) ? 0 : getRoleID().hashCode());
        result = prime * result + ((getAuthID() == null) ? 0 : getAuthID().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastModifyTime() == null) ? 0 : getLastModifyTime().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }
}