package com.mcqueen.mcqueen.model;

import java.io.Serializable;
import java.util.Date;

public class UserRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_User_Role.ID
     *
     * @mbg.generated
     */
    private Integer ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_User_Role.UserID
     *
     * @mbg.generated
     */
    private Integer userID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_User_Role.RoleID
     *
     * @mbg.generated
     */
    private Integer roleID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_User_Role.CreateTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_User_Role.LastModifyTime
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_User_Role.IsDelete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_User_Role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_User_Role.ID
     *
     * @return the value of M_User_Role.ID
     *
     * @mbg.generated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_User_Role.ID
     *
     * @param ID the value for M_User_Role.ID
     *
     * @mbg.generated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_User_Role.UserID
     *
     * @return the value of M_User_Role.UserID
     *
     * @mbg.generated
     */
    public Integer getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_User_Role.UserID
     *
     * @param userID the value for M_User_Role.UserID
     *
     * @mbg.generated
     */
    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_User_Role.RoleID
     *
     * @return the value of M_User_Role.RoleID
     *
     * @mbg.generated
     */
    public Integer getRoleID() {
        return roleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_User_Role.RoleID
     *
     * @param roleID the value for M_User_Role.RoleID
     *
     * @mbg.generated
     */
    public void setRoleID(Integer roleID) {
        this.roleID = roleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_User_Role.CreateTime
     *
     * @return the value of M_User_Role.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_User_Role.CreateTime
     *
     * @param createTime the value for M_User_Role.CreateTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_User_Role.LastModifyTime
     *
     * @return the value of M_User_Role.LastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_User_Role.LastModifyTime
     *
     * @param lastModifyTime the value for M_User_Role.LastModifyTime
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_User_Role.IsDelete
     *
     * @return the value of M_User_Role.IsDelete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_User_Role.IsDelete
     *
     * @param isDelete the value for M_User_Role.IsDelete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_User_Role
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserRole other = (UserRole) that;
        return (this.getID() == null ? other.getID() == null : this.getID().equals(other.getID()))
            && (this.getUserID() == null ? other.getUserID() == null : this.getUserID().equals(other.getUserID()))
            && (this.getRoleID() == null ? other.getRoleID() == null : this.getRoleID().equals(other.getRoleID()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastModifyTime() == null ? other.getLastModifyTime() == null : this.getLastModifyTime().equals(other.getLastModifyTime()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_User_Role
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getID() == null) ? 0 : getID().hashCode());
        result = prime * result + ((getUserID() == null) ? 0 : getUserID().hashCode());
        result = prime * result + ((getRoleID() == null) ? 0 : getRoleID().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastModifyTime() == null) ? 0 : getLastModifyTime().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }
}